
version: '3.7'

volumes:
  db_data:

services:
  db-test:
    image: postgres:12-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor-test
    ports:
      - '5433:5432'
  app-test:
    depends_on:
      - db-test
    build:
      context: .
      dockerfile: testing.Dockerfile
    environment:
      DATABASE_NAME: vapor-test
      DATABASE_USERNAME: vapor_username
      DATABASE_PASSWORD: vapor_password
      DATABASE_PORT: 5432
